study/models.py
from application import db
from user.models import User

class Study(db.Document):
    name = db.StringField(required=True)
    place = db.StringField(required=True)
    location = db.PointField(required=True)
    theme = db.StringField(required=True)
    tag = db.ListField(required=True)
    start_datetime = db.DateTimeField(required=True)
    end_datetime = db.DateTimeField(required=True)
    study_photo = db.StringField()
    description = db.StringField(min_length=50, required=True)
    host = db.ObjectIdField(required=True)
    cancel = db.BooleanField(default=False)
    attendees = db.ListField(db.ReferenceField(User))

class Theme(db.Document):
    name = db.StringField(required=True)
    subscribers = db.ListField(db.ReferenceField(User))
    description = db.StringField(min_length=50, required=True)
    theme_photo = db.StringField()
    cancel = db.BooleanField(default=False)

# class Tag(db.Document):
#     name = db.StringField(required=True)

study/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, DateTimeField, FloatField, SelectField
from wtforms.widgets import TextArea
from flask_wtf.file import FileField, FileAllowed

class BasicStudyForm(FlaskForm):
    name = StringField('Study Name', validators=[validators.DataRequired(), validators.Length(min=2, max=80)])
    theme = SelectField('Theme', validators=[validators.DataRequired()])
    gplace = StringField('Google Place API')
    place = StringField('Place', validators=[validators.DataRequired()], widget=TextArea())
    lng = FloatField('Longitude', validators=[validators.Optional()])
    lat = FloatField('Latitude', validators=[validators.Optional()])
    start_datetime = DateTimeField('Start Time',
                                  validators=[validators.DataRequired()],
                                  format='%Y-%m-%d %H:%M')
    end_datetime = DateTimeField('End Time',
                                validators=[validators.DataRequired()],
                                format='%Y-%m-%d %H:%M')
    photo = FileField('Study photo',
                     validators=[validators.InputRequired(),FileAllowed(['jpg', 'jpeg', 'png', 'gif'],
                                             'Only allow .jpg .png and .gif files')])
    description = StringField('Description', widget=TextArea(), validators=[validators.Length(min=50)])
    tag = StringField('Tag', validators=[validators.DataRequired()])

class EditStudyForm(BasicStudyForm):
    photo = FileField('Study photo',
                     validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'],
                                             'Only allow .jpg .png and .gif files')])

class CancelStudyForm(FlaskForm):
    confirm = StringField('Are you sure you want to cancel this study? (say yes)',
                         validators=[validators.DataRequired()])

class ThemesForm(FlaskForm):
    name = StringField('Name', validators=[validators.DataRequired(), validators.Length(min=2, max=20)])
    description = StringField('Description', widget=TextArea(), validators=[validators.Length(min=10)])
    photo = FileField('Theme photo',
                     validators=[validators.InputRequired(),FileAllowed(['jpg', 'jpeg', 'png', 'gif'],
                                             'Only allow .jpg .png and .gif files')])

class EditThemeForm(ThemesForm):
    photo = FileField('Theme photo',
                     validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'],
                                             'Only allow .jpg .png and .gif files')])

study/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, abort, jsonify
import bson
from study.forms import BasicStudyForm, EditStudyForm, CancelStudyForm, ThemesForm, EditThemeForm
from user.decorators import login_required
from study.models import Study, Theme
from user.models import User
from utilities.storage import upload_image_file
import json


study_page = Blueprint('study_page', __name__)

@study_page.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = BasicStudyForm()
    error = None
    themes = Theme.objects
    form.theme.choices = [theme.name for theme in themes]
    form.theme.choices.insert(0, "---Select A Theme---")
    if request.method == 'POST' and form.validate():
        if form.end_datetime.data < form.start_datetime.data:
            error = "A study must end after it starts!"
        if form.theme.data == "---Select A Theme---":
            error = "Please select a theme!"
        if not error:
            user = User.objects.filter(email=session.get('email')).first()
            study = Study(
                name=form.name.data,
                place=form.place.data,
                location=[form.lng.data, form.lat.data],
                theme = form.theme.data,
                start_datetime=form.start_datetime.data,
                end_datetime=form.end_datetime.data,
                description=form.description.data,
                host=user.id,
                attendees=[user],
                tag = form.tag.data.split(", ")
            )
            study.save()
            image_url = upload_image_file(request.files.get('photo'), 'study_photo', str(study.id))
            if image_url:
                study.study_photo = image_url
            study.save()
            return redirect(url_for('study_page.edit', id=study.id))
    return render_template('study/create.html', form=form, error=error)

@study_page.route('/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit(id):
    try:
        study = Study.objects.filter(id=bson.ObjectId(id)).first()
        study.tag = ", ".join(study.tag)
    except bson.errors.InvalidId:
        abort(404)
    user = User.objects.filter(email=session.get('email')).first()
    if study and study.host == user.id:
        error = None
        message = None
        form = EditStudyForm(obj=study)
        themes = Theme.objects
        form.theme.choices = [theme.name for theme in themes]
        form.theme.choices.insert(0, "---Select A Theme---")
        if request.method == 'POST' and form.validate():
            if form.end_datetime.data < form.start_datetime.data:
                error = 'A study must end after it starts!'
            if form.theme.data == "---Select A Theme---":
                error = "Please select a theme!"
            if not error:
                form.populate_obj(study)
                if form.lng.data and form.lat.data:
                    study.location = [form.lng.data, form.lat.data]
                image_url = upload_image_file(request.files.get('photo'), 'study_photo', str(study.id))
                if image_url:
                    study.study_photo = image_url
                if study.tag:
                    tags = form.tag.data.split(", ")
                    study.tag = tags
                study.save()
                message = 'Study updated'
        return render_template('study/edit.html', form=form, error=error,
                              message=message, study=study)
    else:
        abort(404)

@study_page.route('/<id>/edit_theme', methods=['GET', 'POST'])
@login_required
def edit_theme(id):
    try:
        theme = Theme.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    user = User.objects.filter(email=session.get('email')).first()
    if theme:
        error = None
        message = None
        form = EditThemeForm(obj=theme)
        if request.method == 'POST' and form.validate():
            if not error:
                form.populate_obj(theme)
                image_url = upload_image_file(request.files.get('photo'), 'theme_photo', str(theme.id))
                if image_url:
                    theme.theme_photo = image_url
                theme.save()
                message = 'Theme updated'
        return render_template('study/edit_theme.html', form=form, error=error,
                              message=message, theme=theme)
    else:
        abort(404)

@study_page.route('/<id>/cancel', methods=['GET', 'POST'])
@login_required
def cancel(id):
    try:
        study = Study.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    user = User.objects.filter(email=session.get('email')).first()
    if study and study.host == user.id and study.cancel == False:
        error = None
        form = CancelStudyForm()
        if request.method == 'POST' and form.validate():
            if form.confirm.data == 'yes':
                study.cancel = True
                study.save()
                return redirect(url_for('study_page.edit', id=study.id))
            else:
                error = 'Say yes if you want to cancel'
        return render_template('study/cancel.html', form=form, error=error, study=study)
    else:
        abort(404)

@study_page.route('/<id>', methods=['GET'])
def public(id):
    try:
        study = Study.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if study:
        host = User.objects.filter(id=study.host).first()
        user = User.objects.filter(email=session.get('email')).first()
        return render_template('study/public.html', study=study, host=host, user=user)
    else:
        abort(404)

@study_page.route('/themes/<id>', methods=['GET'])
def public_theme(id):
    try:
        theme = Theme.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if theme:
        user = User.objects.filter(email=session.get('email')).first()
        studies = Study.objects.filter(theme=theme.name,cancel=False)
        return render_template('study/public_theme.html', theme=theme, user=user, studies=studies)
    else:
        abort(404)

@study_page.route('/<id>/join', methods=['GET'])
@login_required
def join(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        study = Study.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user and study:
        if user not in study.attendees:
            study.attendees.append(user)
            study.save()
        return redirect(url_for('study_page.public', id=id))
    else:
        abort(404)

@study_page.route('/<id>/leave', methods=['GET'])
@login_required
def leave(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        study = Study.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user and study:
        if user in study.attendees:
            study.attendees.remove(user)
            study.save()
        return redirect(url_for('study_page.public', id=id))
    else:
        abort(404)

@study_page.route('/<id>/join_theme', methods=['GET'])
@login_required
def join_theme(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        theme = Theme.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user and theme:
        if user not in theme.subscribers:
            theme.subscribers.append(user)
            theme.save()
        return redirect(url_for('study_page.manage_theme', id=id))
    else:
        abort(404)

@study_page.route('/<id>/leave_theme', methods=['GET'])
@login_required
def leave_theme(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        theme = Theme.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user and theme:
        if user in theme.subscribers:
            theme.subscribers.remove(user)
            theme.save()
        return redirect(url_for('study_page.manage_theme', id=id))
    else:
        abort(404)

@study_page.route('/manage', methods=['GET'])
@login_required
def manage():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        studies = Study.objects.filter(host=user.id).order_by('-start_datetime')
        themes = Theme.objects.filter(subscribers=user.id)
        return render_template('study/manage.html', studies=studies, themes = themes, user = user)
    else:
        abort(404)

@study_page.route('/manage_themes', methods=['GET'])
@login_required
def manage_theme():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        themes = Theme.objects.order_by("name")
        return render_template('study/manage_themes.html', themes=themes, user=user)
    else:
        abort(404)

@study_page.route('/create_themes', methods=['GET', 'POST'])
@login_required
def create_themes():
    form = ThemesForm()
    error = None
    if request.method == 'POST' and form.validate():
        if Theme.objects.filter(name=form.name.data).first():
            error = "The tag already exists!"
        if not error:
            user = User.objects.filter(email=session.get('email')).first()
            theme = Theme(
                name=form.name.data,
                description=form.description.data,
                subscribers=[user.id]
            )
            theme.save()
            image_url = upload_image_file(request.files.get('photo'), 'theme_photo', str(theme.id))
            if image_url:
                theme.theme_photo = image_url
            theme.save()
            message = 'Theme created'
            return redirect(url_for('study_page.manage_theme',message=message))

user/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, abort
import bcrypt
import bson

from study.models import Study
from user.models import User
from user.forms import RegistrationForm, LoginForm, EditProfileForm, PasswordForm
from user.decorators import login_required
from utilities.storage import upload_image_file


user_page = Blueprint('user_page', __name__)

@user_page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
        
    if request.method == 'POST' and form.validate():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            if bcrypt.checkpw(form.password.data, user.password):
                session['email'] = user.email   
                return redirect(request.args.get('next') or url_for('home'))
            else:
                user = None
        if not user:
            error = 'Your email or password was entered incorrectly'
    return render_template('user/login.html', form=form, error=error)

@user_page.route('/logout')
def logout():
    session.pop('email')
    return redirect(url_for('user_page.login'))

@user_page.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegistrationForm(request.form)
    if request.method == 'POST' and form.validate():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)
        
        user = User(
            name=form.name.data,
            email=form.email.data.lower(),
            password=hashed_password
        )
        user.save()
        
        return redirect(url_for('user_page.login'))
    return render_template('user/signup.html', form=form)

@user_page.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    user = User.objects.filter(email=session['email']).first()
    if user:
        error = None
        message = None
        form = EditProfileForm(obj=user)
        
        if request.method == 'POST' and form.validate():
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = "Email is already in use"
                else:
                    session['email'] = form.email.data.lower()
            if not error:
                form.populate_obj(user)
                image_url = upload_image_file(request.files.get('image'), 'profile_image', str(user.id))
                print(str(request.files.get('image')))
                if image_url:
                    user.profile_image = image_url
                user.save()
                message = "Profile updated"
                
        return render_template('user/edit.html', user=user, form=form, error=error, message=message)
    else:
        abort(404)
        
@user_page.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        error = None
        message = None
        form = PasswordForm()
        if request.method == 'POST' and form.validate():
            if bcrypt.checkpw(form.old_password.data, user.password):
                salt = bcrypt.gensalt()
                hashed_password = bcrypt.hashpw(form.new_password.data, salt)
                user.password = hashed_password
                user.save()
                message = 'Password updated'
            else:
                error = 'Your old password was incorrect'
        return render_template('user/password.html', form=form, error=error, message=message)
    else:
        abort(404)

@user_page.route('/<id>/<int:study_page_number>', methods=['GET'])
@user_page.route('/<id>')
def profile(id, study_page_number=1):
    try:
        user = User.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user:
        studies = Study.objects(attendees__in=[user], cancel=False).order_by('-start_datetime').paginate(page=study_page_number, per_page=4)
        return render_template('user/profile.html', user=user, studies=studies)
    else:
        abort(404)
        

templates/study/edit_theme.html
{% extends "base.html" %}
{% block title %}Edit Theme{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        {% if theme.theme_photo %}
        <img width="100%" src="{{ theme.theme_photo }}">
        {% else %}
        <img width="100%" src="{{ url_for('static', filename='img/study.png') }}">
        {% endif %}

        <div class="text-center">
            <h3>
                Edit Theme
            </h3>
            <h6>
                <a href="{{ url_for('study_page.public_theme', id=theme.id) }}">Preview</a>
            </h6>
        </div>
        {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endif %}

        {% if message %}
        <div class="alert alert-success">
            {{ message }}
        </div>
        {% endif %}

        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('study_page.edit_theme', id=theme.id) }}" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.name, class="form-control", readonly=true) }}
            {{ render_field(form.photo, class="form-control") }}
            {{ render_field(form.description, class="form-control", rows="8", minlength="50") }}

            {% if theme.cancel %}
            This theme is canceled
            {% else %}
            <button type="submit" class="btn btn-success">
                Save
            </button>
            <!-- <a class="btn btn-secondary" href="{{ url_for('study_page.cancel', id=theme.id) }}">Cancel study</a> -->
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
{% include "googleapi.html" %}
{% endblock %}

templates/study/manage.html
{% extends "base.html" %}
{% block title %}Manange Study{% endblock %}
{% block content %}

<h1>
    My Studies
</h1>
<br>
<div class="row">
    {% for study in studies %}
    <div class="col-md-6 study-item">
        <div class="card">
          <a href="{{ url_for('study_page.public', id=study.id) }}" >
          {% if study.study_photo %}
          <img class="card-img-top study-photo-item" src="{{ study.study_photo}}">
          {% else %}
          <img class="card-img-top study-photo-item" src="{{ url_for('static', filename='img/study.png')}}">
          {% endif %}
          <div class="card-block">
              <h4 class="card-title">
                  {{ study.name }}
              </h4>
          </a>
                <p class="card-text">
                    {{ study.description[:150] }}
                </p>
                <p class="card-text">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <a href="http://maps.google.com?q={{ study.place }}">
                    {{ study.place }}
                    </a>
                    <br>
                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                    {{ study.start_datetime.strftime("%Y-%m-%d %I:%M%p") }}
                    <br>
                    <i class="fa fa-users" aria-hidden="true"></i>
                    {{ study.attendees|length }} attending
                    <br>
                    <i class="fa fa-users" aria-hidden="true"></i>
                    Theme: {{ study.theme }}
                    <br>
                    <i class="fa fa-tag" aria-hidden="true"></i>
                    Tag:
                    {% for tag in study.tag %}
                      {% if study.tag.index(tag) != (study.tag|length - 1)%}
                        {{ tag }},
                      {% else %}
                        {{ tag }}
                      {% endif %}
                    {% endfor %}
                </p>
                {% if study.cancel %}
                <button class="btn btn-danger">
                    Canceled
                </button>
                {% else %}
                <a href="{{ url_for('study_page.edit', id=study.id) }}" class="btn btn-success">
                    Edit
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<h1>
    My Themes
</h1>
<br>
<div class="row">
        {% for theme in themes %}
        <div class="col-md-6 study-item">
            <div class="card">
                {% if theme.theme_photo %}
                <img class="card-img-top study-photo-item" src="{{ theme.theme_photo}}">
                {% else %}
                <img class="card-img-top study-photo-item" src="{{ url_for('static', filename='img/study.png')}}">
                {% endif %}
                <div class="card-block">
                    <a href="{{ url_for('study_page.public_theme', id=theme.id) }}">
                        <h4 class="card-title">
                            {{ theme.name }}
                        </h4>
                    </a>
                    <p class="card-text">
                        {{ theme.description[:150] }}
                    </p>

                    <p>
                        {% if user in theme.subscribers %}
                            <a href="{{ url_for('study_page.leave_theme', id=theme.id) }}" class="btn btn-danger">Unsubscribe</a>
                        {% else %}
                            <a href="{{ url_for('study_page.join_theme', id=theme.id) }}" class="btn btn-success">Subscribe</a>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/study/manage_themes.html
{% extends "base.html" %}
{% block title %}Manange Theme{% endblock %}
{% block content %}

<h1>
    Themes
</h1>
<br>
{% if error %}
<div class="alert alert-danger">
    {{ error }}
</div>
{% endif %}

{% if message %}
<div class="alert alert-success">
    {{ message }}
</div>
{% endif %}

<div class="row">
    {% for theme in themes %}
    <div class="col-md-6 study-item">
        <div class="card">
            {% if theme.theme_photo %}
            <img class="card-img-top study-photo-item" src="{{ theme.theme_photo}}">
            {% else %}
            <img class="card-img-top study-photo-item" src="{{ url_for('static', filename='img/study.png')}}">
            {% endif %}
            <div class="card-block">
                <a href="{{ url_for('study_page.public_theme', id=theme.id) }}">
                    <h4 class="card-title">
                        {{ theme.name }}
                    </h4>
                </a>
                <p class="card-text">
                    {{ theme.description[:150] }}
                </p>
                <p>
                    {% if user in theme.subscribers %}
                        <a href="{{ url_for('study_page.leave_theme', id=theme.id) }}" class="btn btn-danger">Unsubscribe</a>
                    {% else %}
                        <a href="{{ url_for('study_page.join_theme', id=theme.id) }}" class="btn btn-success">Subscribe</a>
                    {% endif %}
                    <a href="{{ url_for('study_page.edit_theme', id=theme.id) }}" class="btn btn-success">Edit</a>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/study/public.html
{% extends "base.html" %}
{% block title %}{{ study.name }}{% endblock %}
{% block content %}

<h3>
    {{ study.name }}
</h3>
<p class="text-muted">
    Hosted by
    <a href="{{ url_for('user_page.profile', id=study.host) }}">{{ host.name }}</a>
    {% if session.email == host.email %}
    <a href="{{ url_for('study_page.edit', id=study.id) }}">Edit</a>
    {% endif %}
</p>

<div class="row">
    <div class="col-md-8">
        {% if study.study_photo %}
        <img width="100%" src="{{ study.study_photo }}">
        {% else %}
        <img width="100%" src="{{ url_for('static', filename='img/study.png') }}">
        {% endif %}
    </div>

    <div class="col-md-4">
        <h6>
            Start Time
        </h6>
        <p>
            <i class="fa fa-clock-o" aria-hidden="true"></i>
            {{ study.start_datetime.strftime("%Y-%m-%d %I:%M%p") }}
        </p>
        <h6>
            End Time
        </h6>
        <p>
            <i class="fa fa-clock-o" aria-hidden="true"></i>
            {{ study.end_datetime.strftime("%Y-%m-%d %I:%M%p") }}
        </p>
        <h6>
            Place
        </h6>
        <p>
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <a href="http://maps.google.com?q={{ study.place }}">
                {{ study.place }}
                </a>
            </p>
        <h6>
            Theme
        </h6>
        <p>
            <i class="fa fa-map-marker" aria-hidden="true"></i>
            {{ study.theme }}
        </p>
        <h6>
            Tag
        </h6>
        <p>
            <i class="fa fa-tag" aria-hidden="true"></i>
            {% for tag in study.tag %}
              {% if study.tag.index(tag) != (study.tag|length - 1)%}
                {{ tag }},
              {% else %}
                {{ tag }}
              {% endif %}
            {% endfor %}
        </p>

        {% if study.cancel %}
        This study has been canceled.
        {% elif session['email'] == host.email %}
        {% elif user in study.attendees %}
        <a href="{{ url_for('study_page.leave', id=study.id) }}" class="btn btn-danger">Leave</a>
        {% else %}
        <a href="{{ url_for('study_page.join', id=study.id) }}" class="btn btn-success">Join</a>
        {% endif %}
    </div>
</div>

<hr>
<h3>
    Description
</h3>
<div class="row">
    <div class="col-md-12">
        <p>
            {{ study.description}}
        </p>
    </div>
</div>

<hr>
<h3>
    Attendees
</h3>
<div class="row">
    {% for user in study.attendees %}
    <div class="col-md-3 text-center">
        <a href="{{ url_for('user_page.profile', id=user.id) }}">
        {% if user.profile_image %}
            <img width="150px" height="150px" src="{{ user.profile_image }}"
                 class="img-thumbnail rounded-circle">
        {% else %}
            <img width="150px" height="150px" src="{{ url_for('static', filename='img/user.png')}}"
                 class="img-thumbnail rounded-circle">
        {% endif %}
            <p>
                {{ user.name }}
            </p>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/study/public_theme.html
{% extends "base.html" %}
{% block title %}{{ theme.name }}{% endblock %}
{% block content %}

<h3>
    {{ theme.name }}
</h3>
<br>
<div class="row">
    <div class="col-md-4">
        {% if user in theme.subscribers %}
            <a href="{{ url_for('study_page.leave_theme', id=theme.id) }}" class="btn btn-danger">Unsubscribe</a>
        {% else %}
            <a href="{{ url_for('study_page.join_theme', id=theme.id) }}" class="btn btn-success">Subscribe</a>
        {% endif %}
    </div>
</div>
<br>
<hr>
<h3>
    Description
</h3>
<div class="row">
    <div class="col-md-12">
        <p>
            {{ theme.description}}
        </p>
    </div>
</div>
<br>
<hr>
<h3>
    Subscribers
</h3>
<div class="row">
    {% for user in theme.subscribers %}
    <div class="col-md-3 text-center">
        <a href="{{ url_for('user_page.profile', id=user.id) }}">
        {% if user.profile_image %}
            <img width="150px" height="150px" src="{{ user.profile_image }}"
                 class="img-thumbnail rounded-circle">
        {% else %}
            <img width="150px" height="150px" src="{{ url_for('static', filename='img/user.png')}}"
                 class="img-thumbnail rounded-circle">
        {% endif %}
            <p>
                {{ user.name }}
            </p>
        </a>
    </div>
    {% endfor %}
</div>
<br>
<hr>
<h3>
    Associated Studies
</h3>
<br>
<div class="row">
    {% for study in studies %}
    <div class="col-md-6 study-item">
        <div class="card">
          <a href="{{ url_for('study_page.public', id=study.id) }}">
            {% if study.study_photo %}
            <img class="card-img-top study-photo-item" src="{{ study.study_photo}}">
            {% else %}
            <img class="card-img-top study-photo-item" src="{{ url_for('static', filename='img/study.png')}}">
            {% endif %}
            <div class="card-block">
                <h4 class="card-title">
                    {{ study.name }}
                </h4>
            </a>
                <p class="card-text">
                    {{ study.description[:150] }}
                </p>
                <p class="card-text">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <a href="http://maps.google.com?q={{ study.place }}" >
                    {{ study.place }}
                    </a>
                    <br>
                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                    {{ study.start_datetime.strftime("%Y-%m-%d %I:%M%p") }}
                    <br>
                    <i class="fa fa-users" aria-hidden="true"></i>
                    {{ study.attendees|length }} attending
                    <br>
                    <i class="fa fa-users" aria-hidden="true"></i>
                    Theme: {{ study.theme }}
                    <br>
                    <i class="fa fa-tag" aria-hidden="true"></i>
                    Tag:
                    {% for tag in study.tag %}
                      {% if study.tag.index(tag) != (study.tag|length - 1)%}
                        {{ tag }},
                      {% else %}
                        {{ tag }}
                      {% endif %}
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}