study/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, abort, jsonify
import bson
from study.forms import BasicStudyForm, EditStudyForm, CancelStudyForm, ThemesForm, EditThemeForm
from user.decorators import login_required
from study.models import Study, Theme
from user.models import User
from utilities.storage import upload_image_file
import json


study_page = Blueprint('study_page', __name__)

@study_page.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = BasicStudyForm()
    error = None
    themes = Theme.objects
    form.theme.choices = [theme.name for theme in themes]
    form.theme.choices.insert(0, "---Select A Theme---")
    if request.method == 'POST' and form.validate():
        if form.end_datetime.data < form.start_datetime.data:
            error = "A study must end after it starts!"
        if form.theme.data == "---Select A Theme---":
            error = "Please select a theme!"
        if not error:
            user = User.objects.filter(email=session.get('email')).first()
            study = Study(
                name=form.name.data,
                place=form.place.data,
                location=[form.lng.data, form.lat.data],
                theme = form.theme.data,
                start_datetime=form.start_datetime.data,
                end_datetime=form.end_datetime.data,
                description=form.description.data,
                host=user.id,
                attendees=[user],
                tag = form.tag.data.split(", ")
            )
            study.save()
            image_url = upload_image_file(request.files.get('photo'), 'study_photo', str(study.id))
            if image_url:
                study.study_photo = image_url
            study.save()
            return redirect(url_for('study_page.edit', id=study.id))
    return render_template('study/create.html', form=form, error=error)

@study_page.route('/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit(id):
    try:
        study = Study.objects.filter(id=bson.ObjectId(id)).first()
        study.tag = ", ".join(study.tag)
    except bson.errors.InvalidId:
        abort(404)
    user = User.objects.filter(email=session.get('email')).first()
    if study and study.host == user.id:
        error = None
        message = None
        form = EditStudyForm(obj=study)
        themes = Theme.objects
        form.theme.choices = [theme.name for theme in themes]
        form.theme.choices.insert(0, "---Select A Theme---")
        if request.method == 'POST' and form.validate():
            if form.end_datetime.data < form.start_datetime.data:
                error = 'A study must end after it starts!'
            if form.theme.data == "---Select A Theme---":
                error = "Please select a theme!"
            if not error:
                form.populate_obj(study)
                if form.lng.data and form.lat.data:
                    study.location = [form.lng.data, form.lat.data]
                image_url = upload_image_file(request.files.get('photo'), 'study_photo', str(study.id))
                if image_url:
                    study.study_photo = image_url
                if study.tag:
                    tags = form.tag.data.split(", ")
                    study.tag = tags
                study.save()
                message = 'Study updated'
        return render_template('study/edit.html', form=form, error=error,
                              message=message, study=study)
    else:
        abort(404)

@study_page.route('/<id>/edit_theme', methods=['GET', 'POST'])
@login_required
def edit_theme(id):
    try:
        theme = Theme.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    user = User.objects.filter(email=session.get('email')).first()
    if theme:
        error = None
        message = None
        form = EditThemeForm(obj=theme)
        if request.method == 'POST' and form.validate():
            if not error:
                form.populate_obj(theme)
                image_url = upload_image_file(request.files.get('photo'), 'theme_photo', str(theme.id))
                if image_url:
                    theme.theme_photo = image_url
                theme.save()
                message = 'Theme updated'
        return render_template('study/edit_theme.html', form=form, error=error,
                              message=message, theme=theme)
    else:
        abort(404)

@study_page.route('/<id>/cancel', methods=['GET', 'POST'])
@login_required
def cancel(id):
    try:
        study = Study.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    user = User.objects.filter(email=session.get('email')).first()
    if study and study.host == user.id and study.cancel == False:
        error = None
        form = CancelStudyForm()
        if request.method == 'POST' and form.validate():
            if form.confirm.data == 'yes':
                study.cancel = True
                study.save()
                return redirect(url_for('study_page.edit', id=study.id))
            else:
                error = 'Say yes if you want to cancel'
        return render_template('study/cancel.html', form=form, error=error, study=study)
    else:
        abort(404)

@study_page.route('/<id>', methods=['GET'])
def public(id):
    try:
        study = Study.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if study:
        host = User.objects.filter(id=study.host).first()
        user = User.objects.filter(email=session.get('email')).first()
        return render_template('study/public.html', study=study, host=host, user=user)
    else:
        abort(404)

@study_page.route('/themes/<id>', methods=['GET'])
def public_theme(id):
    try:
        theme = Theme.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if theme:
        user = User.objects.filter(email=session.get('email')).first()
        studies = Study.objects.filter(theme=theme.name,cancel=False)
        return render_template('study/public_theme.html', theme=theme, user=user, studies=studies)
    else:
        abort(404)

@study_page.route('/<id>/join', methods=['GET'])
@login_required
def join(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        study = Study.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user and study:
        if user not in study.attendees:
            study.attendees.append(user)
            study.save()
        return redirect(url_for('study_page.public', id=id))
    else:
        abort(404)

@study_page.route('/<id>/leave', methods=['GET'])
@login_required
def leave(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        study = Study.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user and study:
        if user in study.attendees:
            study.attendees.remove(user)
            study.save()
        return redirect(url_for('study_page.public', id=id))
    else:
        abort(404)

@study_page.route('/<id>/join_theme', methods=['GET'])
@login_required
def join_theme(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        theme = Theme.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user and theme:
        if user not in theme.subscribers:
            theme.subscribers.append(user)
            theme.save()
        return redirect(url_for('study_page.manage_theme', id=id))
    else:
        abort(404)

@study_page.route('/<id>/leave_theme', methods=['GET'])
@login_required
def leave_theme(id):
    user = User.objects.filter(email=session.get('email')).first()
    try:
        theme = Theme.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user and theme:
        if user in theme.subscribers:
            theme.subscribers.remove(user)
            theme.save()
        return redirect(url_for('study_page.manage_theme', id=id))
    else:
        abort(404)

@study_page.route('/manage', methods=['GET'])
@login_required
def manage():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        studies = Study.objects.filter(host=user.id).order_by('-start_datetime')
        themes = Theme.objects.filter(subscribers=user.id)
        return render_template('study/manage.html', studies=studies, themes = themes, user = user)
    else:
        abort(404)

@study_page.route('/manage_themes', methods=['GET'])
@login_required
def manage_theme():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        themes = Theme.objects.order_by("name")
        return render_template('study/manage_themes.html', themes=themes, user=user)
    else:
        abort(404)

@study_page.route('/create_themes', methods=['GET', 'POST'])
@login_required
def create_themes():
    form = ThemesForm()
    error = None
    if request.method == 'POST' and form.validate():
        if Theme.objects.filter(name=form.name.data).first():
            error = "The tag already exists!"
        if not error:
            user = User.objects.filter(email=session.get('email')).first()
            theme = Theme(
                name=form.name.data,
                description=form.description.data,
                subscribers=[user.id]
            )
            theme.save()
            image_url = upload_image_file(request.files.get('photo'), 'theme_photo', str(theme.id))
            if image_url:
                theme.theme_photo = image_url
            theme.save()
            message = 'Theme created'
            return redirect(url_for('study_page.manage_theme',message=message))

user/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, abort
import bcrypt
import bson

from study.models import Study
from user.models import User
from user.forms import RegistrationForm, LoginForm, EditProfileForm, PasswordForm
from user.decorators import login_required
from utilities.storage import upload_image_file


user_page = Blueprint('user_page', __name__)

@user_page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
        
    if request.method == 'POST' and form.validate():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            if bcrypt.checkpw(form.password.data, user.password):
                session['email'] = user.email   
                return redirect(request.args.get('next') or url_for('home'))
            else:
                user = None
        if not user:
            error = 'Your email or password was entered incorrectly'
    return render_template('user/login.html', form=form, error=error)

@user_page.route('/logout')
def logout():
    session.pop('email')
    return redirect(url_for('user_page.login'))

@user_page.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegistrationForm(request.form)
    if request.method == 'POST' and form.validate():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)
        
        user = User(
            name=form.name.data,
            email=form.email.data.lower(),
            password=hashed_password
        )
        user.save()
        
        return redirect(url_for('user_page.login'))
    return render_template('user/signup.html', form=form)

@user_page.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    user = User.objects.filter(email=session['email']).first()
    if user:
        error = None
        message = None
        form = EditProfileForm(obj=user)
        
        if request.method == 'POST' and form.validate():
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = "Email is already in use"
                else:
                    session['email'] = form.email.data.lower()
            if not error:
                form.populate_obj(user)
                image_url = upload_image_file(request.files.get('image'), 'profile_image', str(user.id))
                print(str(request.files.get('image')))
                if image_url:
                    user.profile_image = image_url
                user.save()
                message = "Profile updated"
                
        return render_template('user/edit.html', user=user, form=form, error=error, message=message)
    else:
        abort(404)
        
@user_page.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        error = None
        message = None
        form = PasswordForm()
        if request.method == 'POST' and form.validate():
            if bcrypt.checkpw(form.old_password.data, user.password):
                salt = bcrypt.gensalt()
                hashed_password = bcrypt.hashpw(form.new_password.data, salt)
                user.password = hashed_password
                user.save()
                message = 'Password updated'
            else:
                error = 'Your old password was incorrect'
        return render_template('user/password.html', form=form, error=error, message=message)
    else:
        abort(404)

@user_page.route('/<id>/<int:study_page_number>', methods=['GET'])
@user_page.route('/<id>')
def profile(id, study_page_number=1):
    try:
        user = User.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user:
        studies = Study.objects(attendees__in=[user], cancel=False).order_by('-start_datetime').paginate(page=study_page_number, per_page=4)
        return render_template('user/profile.html', user=user, studies=studies)
    else:
        abort(404)
        

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
    {{ field.label }}
    {{ field(**kwargs)|safe }}
    {% if field.errors %}
        <ul class="text-danger">
        {% for error in field.errors %}
            <li>{{ error}}</li>
        {% endfor %}
        </ul>
    {% endif %}
</div>
{% endmacro %}

templates/base.html
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

  <!-- Stylesheets -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <style>
    .container {
      padding-top: 100px;
    }
  </style>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <a class="navbar-brand" href="/">StudyGo</a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item {% if request.endpoint == 'map' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('map') }}">Map</a>
        </li>
        <li class="nav-item {% if request.endpoint == 'study_page.search' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('study_page.search') }}">Search</a>
        </li>
        <li class="nav-item {% if request.endpoint == 'study_page.create' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('study_page.create') }}">Create Study</a>
        </li>
        <li class="nav-item {% if request.endpoint == 'study_page.create_themes' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('study_page.create_themes') }}">Create Theme</a>
        </li>
        <li class="nav-item {% if request.endpoint == 'study_page.manage_theme' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('study_page.manage_theme') }}">Manage Themes</a>
        </li>
        {% if session.email %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" id="navbarsExampleDefault" aria-haspopup="true" aria-expanded="false">{{ session.email }}</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('user_page.edit') }}">Edit Profile</a>
            <a class="dropdown-item" href="{{ url_for('user_page.password') }}">Change Password</a>
            <a class="dropdown-item" href="{{ url_for('study_page.manage') }}">My Studies</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user_page.logout') }}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item {% if request.endpoint == 'user_page.login' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('user_page.login') }}">Log In</a>
        </li>
        <li class="nav-item {% if request.endpoint == 'user_page.signup' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('user_page.signup') }}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

  {% block javascript %}{% endblock %}
</body>

</html>

templates/googleapi.html
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyASUQZwsk2RX9ZzZJ6xGBHJgfoJCJW9ebk&libraries=places&callback=initAutocomplete" async defer></script>

<script>
    function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */
            (document.getElementById('autocomplete')), {
                types: ['geocode']
            });

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
    }

    function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();
        document.getElementById('place').value = place.formatted_address;
        document.getElementById('lng').value = place.geometry.location.lng();
        document.getElementById('lat').value = place.geometry.location.lat();
        
    }
</script>

templates/map.html
{% extends "base.html" %}
{% block title %}Map{% endblock %}
{% block content %}
<head>
  <script src="//maps.googleapis.com/maps/api/js?key=AIzaSyCRQzAIwUhY_dp-FhBEdtxzNZQ2m0_zvdQ&language=en&region=US" type="text/javascript"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/js-marker-clusterer/1.0.0/markerclusterer_compiled.js" type="text/javascript"></script>
<style type="text/css">
      #sndmap { height:80%;width:100%; }
</style>
<script type="text/javascript">
    var map = null;
    var map_markers = [];
    var map_rectangles = [];
    var map_circles = [];
    var map_polygons = [];
    var map_polylines = [];
    var prev_infowindow_map = null;
    var current_infowindow_map = null;

    function initialize_map() {
        document.getElementById('sndmap').style.display = 'block';
        map = new google.maps.Map(
        document.getElementById('sndmap'), {
            center: new google.maps.LatLng(30.2880433, -97.7308176),
            zoom: 12,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            zoomControl: true,
            mapTypeControl: true,
            scaleControl: true,
            streetViewControl: true,
            rotateControl: true,
            scrollwheel: true,
            fullscreenControl: true
        });

        //center map location on user location


        // add gmap markers
        var data = {{ data|tojson }};
        var raw_markers = data;
        for(i=0; i<raw_markers.length;i++) {
            map_markers[i] = new google.maps.Marker({
                position: new google.maps.LatLng(raw_markers[i].lat, raw_markers[i].lng),
                map: map,
                icon: raw_markers[i].icon,
                title: raw_markers[i].title ? raw_markers[i].title : null
            });

           if(raw_markers[i].infobox)
           {
              console.log(map)
                google.maps.event.addListener(
                        map_markers[i],
                        'mouseover',
                        getInfoCallback(map, raw_markers[i].infobox)
                );

           }
        }
        var markerCluster = new MarkerClusterer(map, map_markers, {'imagePath': "https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m", 'gridSize': 60});





        // add rectangles
        var raw_rectangles = [];
        for(i = 0; i < 0; i++) {
            map_rectangles[i] = new google.maps.Rectangle({
                strokeColor: raw_rectangles[i].stroke_color,
                strokeOpacity: raw_rectangles[i].stroke_opacity,
                strokeWeight: raw_rectangles[i].stroke_weight,
                fillColor: raw_rectangles[i].fill_color,
                fillOpacity: raw_rectangles[i].fill_opacity,
                map: map,
                bounds: {
                    north: raw_rectangles[i].bounds.north,
                    east: raw_rectangles[i].bounds.east,
                    south: raw_rectangles[i].bounds.south,
                    west: raw_rectangles[i].bounds.west },
            });

           if(raw_rectangles[i].infobox)
           {
                google.maps.event.addListener(
                        map_rectangles[i],
                        'click',
                        getInfoCallback(map, raw_rectangles[i].infobox)
                );
           }
        }

        // add circles
        var raw_circles = [];
        for(i = 0; i < 0; i++) {
            map_circles[i] = new google.maps.Circle({
                strokeColor: raw_circles[i].stroke_color,
                strokeOpacity: raw_circles[i].stroke_opacity,
                strokeWeight: raw_circles[i].stroke_weight,
                fillColor: raw_circles[i].fill_color,
                fillOpacity: raw_circles[i].fill_opacity,
                map: map,
                center: {
                    lat: raw_circles[i].center.lat,
                    lng: raw_circles[i].center.lng,
                },
                radius: raw_circles[i].radius
            });

           if(raw_circles[i].infobox)
           {
                google.maps.event.addListener(
                        map_circles[i],
                        'click',
                        getInfoCallback(map, raw_circles[i].infobox)
                );
           }
        }

        // add polygons
        var raw_polygons = [];
        for(i = 0; i < 0; i++) {
            map_polygons[i] = new google.maps.Polygon({
                strokeColor: raw_polygons[i].stroke_color,
                strokeOpacity: raw_polygons[i].stroke_opacity,
                strokeWeight: raw_polygons[i].stroke_weight,
                fillOpacity: raw_polygons[i].fill_opacity,
                fillColor: raw_polygons[i].fill_color,
                path: raw_polygons[i].path,
                map: map,
                geodesic: true
            });

           if(raw_polygons[i].infobox)
           {
                google.maps.event.addListener(
                        map_polygons[i],
                        'click',
                        getInfoCallback(map, raw_polygons[i].infobox)
                );
           }
        }

        // add polylines
        var raw_polylines = [];
        for(i = 0; i < 0; i++) {
            map_polylines[i] = new google.maps.Polyline({
                strokeColor: raw_polylines[i].stroke_color,
                strokeOpacity: raw_polylines[i].stroke_opacity,
                strokeWeight: raw_polylines[i].stroke_weight,
                path: raw_polylines[i].path,
                map: map,
                geodesic: true
            });

           if(raw_polylines[i].infobox)
           {
                google.maps.event.addListener(
                        map_polylines[i],
                        'click',
                        getInfoCallback(map, raw_polylines[i].infobox)
                );
           }
        }


    }

    function getInfoCallback(map, content) {
        var infowindow = new google.maps.InfoWindow({content: content, map: map});
        return function(ev) {

            if( prev_infowindow_map ) {
                prev_infowindow_map.close();
            }
            current_infowindow_map = infowindow
            prev_infowindow_map = infowindow;
            infowindow.setPosition(ev.latLng);
            infowindow.setContent(content);
            infowindow.open(map, this);
        };
    }

    function clickposCallback(uri, latLng) {
    	xhttp = new XMLHttpRequest();
    	xhttp.open("POST", uri);
    	xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhttp.send("lat=" + latLng.lat() + "&lng="  + latLng.lng());
    }


        google.maps.event.addDomListener(window, 'load', initialize_map);


</script>
  </head>
  <body>
    {{sndmap.html}}
  </body>

  {% endblock %}