user/models.py
from application import db
import datetime

class User(db.Document):
    name = db.StringField(required=True)
    email = db.StringField(required=True, unique=True)
    password = db.StringField(required=True)
    created = db.DateTimeField(default=datetime.datetime.now)
    bio = db.StringField(max_length=200)
    profile_image = db.StringField()

user/forms.py
from flask_wtf import FlaskForm
from wtforms import Form, StringField, PasswordField, validators, ValidationError
from wtforms.fields.html5 import EmailField
from wtforms.widgets import TextArea
from flask_wtf.file import FileField, FileAllowed

from user.models import User

class BaseUserForm(FlaskForm):
    name = StringField('Your name', [validators.DataRequired(), validators.Length(min=2, max=30)])
    email = EmailField('Email Address', [validators.DataRequired(), validators.Email()])   

class RegistrationForm(BaseUserForm):
    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match')
    ])
    confirm = PasswordField('Repeat Password')
    
    def validate_email(FlaskForm, field):
        if User.objects.filter(email=field.data.lower()).first():
            raise ValidationError('Email address already in use')

class EditProfileForm(BaseUserForm):
    image = FileField('Profile image',
                     validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'],
                                             'Only allow .jpg .png and .gif files')])
    bio = StringField('Bio',
                     widget=TextArea(),
                     validators=[validators.Length(max=200)])
    
class LoginForm(FlaskForm):
    email = EmailField('Email Address', [validators.DataRequired(), validators.Email()])
    password = PasswordField('Password', [validators.DataRequired()])
    
class PasswordForm(FlaskForm):
    old_password = PasswordField('Old Password', [validators.DataRequired()])
    new_password = PasswordField('New Password', [validators.DataRequired(),
                                                 validators.EqualTo('confirm',
                                                                    message='Passwords must match')])
    confirm = PasswordField('Confirm Password')
    

user/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, abort
import bcrypt
import bson

from study.models import Study
from user.models import User
from user.forms import RegistrationForm, LoginForm, EditProfileForm, PasswordForm
from user.decorators import login_required
from utilities.storage import upload_image_file


user_page = Blueprint('user_page', __name__)

@user_page.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    error = None
        
    if request.method == 'POST' and form.validate():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            if bcrypt.checkpw(form.password.data, user.password):
                session['email'] = user.email   
                return redirect(request.args.get('next') or url_for('home'))
            else:
                user = None
        if not user:
            error = 'Your email or password was entered incorrectly'
    return render_template('user/login.html', form=form, error=error)

@user_page.route('/logout')
def logout():
    session.pop('email')
    return redirect(url_for('user_page.login'))

@user_page.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegistrationForm(request.form)
    if request.method == 'POST' and form.validate():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)
        
        user = User(
            name=form.name.data,
            email=form.email.data.lower(),
            password=hashed_password
        )
        user.save()
        
        return redirect(url_for('user_page.login'))
    return render_template('user/signup.html', form=form)

@user_page.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    user = User.objects.filter(email=session['email']).first()
    if user:
        error = None
        message = None
        form = EditProfileForm(obj=user)
        
        if request.method == 'POST' and form.validate():
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = "Email is already in use"
                else:
                    session['email'] = form.email.data.lower()
            if not error:
                form.populate_obj(user)
                image_url = upload_image_file(request.files.get('image'), 'profile_image', str(user.id))
                print(str(request.files.get('image')))
                if image_url:
                    user.profile_image = image_url
                user.save()
                message = "Profile updated"
                
        return render_template('user/edit.html', user=user, form=form, error=error, message=message)
    else:
        abort(404)
        
@user_page.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = User.objects.filter(email=session.get('email')).first()
    if user:
        error = None
        message = None
        form = PasswordForm()
        if request.method == 'POST' and form.validate():
            if bcrypt.checkpw(form.old_password.data, user.password):
                salt = bcrypt.gensalt()
                hashed_password = bcrypt.hashpw(form.new_password.data, salt)
                user.password = hashed_password
                user.save()
                message = 'Password updated'
            else:
                error = 'Your old password was incorrect'
        return render_template('user/password.html', form=form, error=error, message=message)
    else:
        abort(404)

@user_page.route('/<id>/<int:study_page_number>', methods=['GET'])
@user_page.route('/<id>')
def profile(id, study_page_number=1):
    try:
        user = User.objects.filter(id=bson.ObjectId(id)).first()
    except bson.errors.InvalidId:
        abort(404)
    if user:
        studies = Study.objects(attendees__in=[user], cancel=False).order_by('-start_datetime').paginate(page=study_page_number, per_page=4)
        return render_template('user/profile.html', user=user, studies=studies)
    else:
        abort(404)
        

templates/user/edit.html
{% extends "base.html" %}
{% block title %}Edit Profile{% endblock %}
{% block content %}
<div clas="row">
    <div class="col-md-6 offset-md-3">
        
        <div class="text-center">
            {% if user.profile_image %}
            <img width="150px" height="150px" src="{{ user.profile_image }}" class="img-thumbnail rounded-circle">
            {% else %}
            <img width="150px" height="150px" src="{{ url_for('static', filename='img/user.png')}}" class="img-thumbnial rounded-circle">
            {% endif %}
        
            <h3>
                Edit Profile
            </h3>
        </div>
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        
        {% if message %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endif %}
        
        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('user_page.edit') }}" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.name, class="form-control") }}
            {{ render_field(form.email, class="form-control") }}
            {{ render_field(form.image, class="form-control") }}
            {{ render_field(form.bio, rows="3", class="form-control") }}
            
            <button type="submit" class="btn btn-success">
                Save
            </button>
        </form>
    </div>
</div>
{% endblock %}

templates/user/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>
            StudyGo Login
        </h3>
        
        {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endif %}
        
        {% from "_formhelpers.html" import render_field %}
        <form method="POST">
            
            {{ form.csrf_token }}
            {{ render_field(form.email, class="form-control", placeholder="Enter your email") }}
            {{ render_field(form.password, class="form-control" )}}
            
            <button type="submit" class="btn btn-success">
                Login
            </button>
        </form>
    </div>   
</div>
{% endblock %}

templates/user/password.html
{% extends "base.html" %}
{% block title %}Change Your Password{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="text-center">
            <h3>
                Change Your Password
            </h3>            
        </div>
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        {% if message %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endif %}
        
        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('user_page.password')}}">
            
            {{ form.csrf_token }}
            {{ render_field(form.old_password, class="form-control") }}
            {{ render_field(form.new_password, class="form-control") }}
            {{ render_field(form.confirm, class="form-control") }}
            
            <button type="submit" class="btn btn-success">
                Update Password
            </button>
        </form>
    </div>
</div>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %}
{% block title %}{{ user.name }}'s Profile{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="text-center">
            {% if user.profile_image %}
            <img width="150px" height="150px" src="{{ user.profile_image }}" class="img-thumbnail rounded-circle">
            {% else %}
            <img width="150px" height="150px" src="{{ url_for('static', filename='img/user.png') }}" class="img-thrumbnail rounded-circle">
            {% endif %}
            <h3>
                {{ user.name }}
            </h3>
            
            <p>
                {% if user.bio %}
                {{ user.bio }}
                {% else %}
                Hello everyone, I am a newbie here!
                {% endif %}
            </p>
        </div>
    </div>   
</div>


{% if studies and studies.pages > 0 %}
<p class="text-muted text-center">
    Study I'm going :)
</p>


<div class="row">
    {% for study in studies.items %}
    <div class="col-md-6 study-item">
        <div class="card">
            <a href="{{ url_for('study_page.public', id=study.id) }}" target="_blank">
            {% if study.study_photo %}
            <img class="card-img-top study-photo-item" src="{{ study.study_photo}}">
            {% else %}
            <img class="card-img-top study-photo-item" src="{{ url_for('static', filename='img/study.png')}}">
            {% endif %}
            </a>
            <div class="card-block">
                <h4 class="card-title">
                    {{ study.name }}
                </h4>
                <p class="card-text">
                    {{ study.description[:150] }}
                </p>
                <p class="card-text">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <a href="http://maps.google.com?q={{ study.place }}" target="_blank">
                    {{ study.place }}
                    </a>
                    <br>
                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                    {{ study.start_datetime.strftime("%Y-%m-%d %I:%M%p") }} 
                    <br>
                    <i class="fa fa-users" aria-hidden="true"></i>
                    {{ study.attendees|length }} attending
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="row justify-content-center">
    <ul class="pagination">
        {% if studies.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('user_page.profile',
                                       study_page_number=studies.prev_num, id=user.id) }}">
                <span>&laquo;</span>
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <p class="page-link">
                Page {{ studies.page }} of {{ studies.pages }}
            </p>        
        </li>
        {% if studies.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('user_page.profile', 
                                       study_page_number=studies.next_num, id=user.id) }}">
                <span>&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}
{% endblock %}

templates/user/signup.html
{% extends "base.html" %}
{% block title %}SignUp{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
       <h3>
           Sign Up
        </h3>
       {% from "_formhelpers.html" import render_field %}
       <form method="POST" action="{{ url_for('user_page.signup') }}">
           
           {{ form.csrf_token }}
           {{ render_field(form.name, class="form-control", placeholder="Enter your name") }}
           {{ render_field(form.email, class="form-control") }}
           {{ render_field(form.password, class="form-control") }}
           {{ render_field(form.confirm, class="form-control") }}
           
           <button type="submit" class="btn btn-success">
               Sign Up
           </button>
        </form>
    </div>
</div>
{% endblock %}